### ISSUE TITLE
[SECURITY ISSUE!] Remove your API Key for Syncfusion

### ISSUE THREAD

**Issue by maxreb** [Tommatheussen/ShiftPlanner#6]
Hi,

I stumbled upon your repository as I search for a shiftplanner written in C# so I cloned your repository and saw that you had your API Key publicy in your program.cs

You should remove it ASAP (I would recommend for example [this guide](https://hurricanelabs.com/blog/how-to-easily-remove-an-api-key-from-a-git-repository/)) and you should unregister this API Key from Syncfusion.

Best,
Max

**Comment by Tommatheussen** [comment]
Thanks for the concern!
Actually SyncFusion does not allow unregistering API keys.
On top of that, this is a frontend key, meaning it'll always be readable from the final result, so there really isn't a security concern here in my opinion ;)
